In [1]:
import torch

In [2]:
torch.ones((2,), dtype=torch.int8)

tensor([1, 1], dtype=torch.int8)

In [3]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.ones((2,3),dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [5]:
torch.zeros((2,3), dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [6]:
torch.zeros((2,3)).dtype

torch.float32

In [7]:
torch.empty((2,3))

tensor([[4.7393e+30, 9.5461e-01, 4.4377e+27],
        [1.7975e+19, 4.6894e+27, 7.9463e+08]])

In [8]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [9]:
torch.rand((2,3))

tensor([[0.6296, 0.8501, 0.4154],
        [0.8373, 0.9050, 0.2377]])

In [10]:
torch.randint(10, 100, (2,3))

tensor([[10, 22, 24],
        [33, 69, 64]])

In [11]:
torch.randn((2,3))

tensor([[ 1.2466,  2.0281,  1.2525],
        [ 0.4848, -0.9353, -0.3039]])

In [12]:
torch.tensor([[1, 2 ,3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
torch.as_tensor([[1., 2 ,3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
a = torch.tensor([[1, 2 ,3], [4, 5, 6]])

In [15]:
a.dtype

torch.int64

In [16]:
a.shape

torch.Size([2, 3])

In [17]:
b = torch.ones_like(a)

In [18]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
a.new_tensor([[0., 1.]])

/var/folders/4p/wzkg05fx3b3fwlcnbdn8_myr0000gn/T/ipykernel_48822/4260253721.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a.new_tensor([[0., 1.]])


tensor([[0, 1]])

In [20]:
a.new_full((2,2), 3.)

tensor([[3, 3],
        [3, 3]])

In [21]:
a.size()

torch.Size([2, 3])

In [22]:
a.dtype

torch.int64

In [24]:
b.numel()

6

In [25]:
import numpy as np
a = np.random.rand(2,3)
a

array([[0.61750505, 0.49748974, 0.08325345],
       [0.38324043, 0.74377139, 0.20063317]])

In [26]:
a = np.ones((2, 3))

In [28]:
b = torch.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [29]:
b.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
a *= 2
a

array([[2., 2., 2.],
       [2., 2., 2.]])

In [31]:
b

tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

In [32]:
b.requires_grad

False

In [33]:
a = torch.ones((2,3),requires_grad=True)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [35]:
a = torch.full((2,3), 4., requires_grad=True)
a

tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [37]:
b = (a**2+3).sum()
b

tensor(114., grad_fn=<SumBackward0>)

In [38]:
b.grad_fn

In [39]:
b.requires_grad

True

In [40]:
b.backward()

In [41]:
a.grad

tensor([[8., 8., 8.],
        [8., 8., 8.]])

In [43]:
x = torch.full((2,3), 4.,requires_grad=True)
y = 2*x+3
y

tensor([[11., 11., 11.],
        [11., 11., 11.]], grad_fn=<AddBackward0>)

In [44]:
x = torch.randn(3, requires_grad=True)
print(x.requires_grad)
print((x ** 2).requires_grad)
y = x**2
print(y.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)
    print(y.requires_grad)

True
True
True
False
True


In [45]:
a = torch.Tensor([1, 2, 3, 4])
torch.reshape(a, (2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [46]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.resize_((2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [47]:
torch.arange(1.,7.).resize_(2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [48]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.view((2, -1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [49]:
a = torch.Tensor([[1, 2, 3], 
                    [4, 5, 6]])
b = torch.Tensor([4,5,6,7,8,9])
b.view_as(a)

tensor([[4., 5., 6.],
        [7., 8., 9.]])